<?php

namespace AppBundle\Repository;

/**
 * AffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationRepository extends \Doctrine\ORM\EntityRepository
{     

public  function recapPeriode($startDate=null, $endDate=null,$region=null){
 $qb = $this->createQueryBuilder('a')->leftJoin('a.user', 'u')->join('l.commende', 'c')
 ->join('l.produit', 'p')->leftJoin('a.pointVente','pdv');
  if($region!=null){
        $qb->andWhere('pdv.ville=:ville or pdv.ville is NULL')->setParameter('ville', $region);
      } 
  if($startDate!=null){
         $qb->andWhere('c.date is null or c.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
      }
   if($endDate!=null){
      $qb->andWhere('c.date is null or c.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
    }
   return $qb->getQuery()->getResult();
  }


    public   function findPerformances($startDate=null, $endDate=null,$region=null){

        $qb = $this->createQueryBuilder('a')->join('a.user', 'u')->join('a.pointVente','pdv')->join('a.ressource','ba')
        ->leftJoin('a.commendes','c');
        if($region!=null){
              $qb->andWhere('pdv.ville=:ville or pdv.ville is NULL')->setParameter('ville', $region);
          }
     
         $qb
         ->select('pdv.id as pdvid')
         ->addSelect('a.id')
         ->addSelect('pdv.nom as pdvnom')
         ->addSelect('pdv.type as type')
         ->addSelect('pdv.telephone pdvtelephone')
         ->addSelect('u.id as supid')
         ->addSelect('u.nom as supnom')
         ->addSelect('ba.id as baid')
         ->addSelect('ba.nom as banom')
         ->addSelect('ba.telephone')  
         ->addSelect('count(DISTINCT c.date) as nombrejours')
         ->addGroupBy('a.id')
         ->addGroupBy('pdv.id')
         ->addGroupBy('pdv.nom')
        ->addGroupBy('pdv.type')
         ->addGroupBy('pdv.telephone')
         ->addGroupBy('ba.id')
         ->addGroupBy('ba.nom')
         ->addGroupBy('ba.telephone')
         ->addGroupBy('u.nom')
         ->addGroupBy('u.id');
        return $qb->getQuery()->getArrayResult(); 
  } 


}
