<?php

namespace AppBundle\Repository;
use AppBundle\Entity\PointVente; 
use AppBundle\Entity\User; 
use Doctrine\ORM\NoResultException;
/**
 * CommendeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommendeRepository extends \Doctrine\ORM\EntityRepository
{
	  	 public function findByPointVente(PointVente $pointVente){
           $qb = $this->createQueryBuilder('c')
           ->where('c.pointVente=:pointVente')->setParameter('pointVente', $pointVente);
         return $qb->getQuery()->getResult();  
  }

  	  	public function findList(User $user=null,$startDate=null, $endDate=null){
           $qb = $this->createQueryBuilder('c');
           if($user!=null){
           $qb ->andWhere('c.user=:user')->setParameter('user', $user);
            }
             if($startDate!=null){
           $qb->andWhere('c.date is null or c.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('c.date is null or c.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }
         return $qb->getQuery()->getResult();  
  }


      public  function rapports($startDate=null, $endDate=null){
        $qb = $this->createQueryBuilder('c');
         if($startDate!=null){
              $qb->andWhere('c.date is null or c.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
             $qb->andWhere('c.date is null or c.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }     
         $qb->select('c.typeInsident')
         ->addSelect('count(c.id) as nombre')
         ->addGroupBy('c.typeInsident');
           return $qb->getQuery()->getArrayResult(); 
  } 



    public   function workedDays($startDate=null, $endDate=null,$all=false){

        $qb = $this->createQueryBuilder('c')->innerJoin('c.pointVente','p')->innerJoin('c.lignes','l');
         if($startDate!=null){
              $qb->andWhere('c.date is null or c.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
             $qb->andWhere('c.date is null or c.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }     
         $qb->select('p.id')
         ->addSelect('p.nom')
         ->addSelect('sum(l.quantite) as nombre')
         ->addSelect('count(DISTINCT c.date) as nombrejours')
         ->addGroupBy('p.id')
         ->addGroupBy('p.nom');
          if (!$all) 
           return $qb->getQuery()->setMaxResults(10)->getArrayResult();
        return $qb->getQuery()->getArrayResult(); 
  } 

    public   function totalWorkedDays($startDate=null, $endDate=null){

        $qb = $this->createQueryBuilder('c');
         if($startDate!=null){
              $qb->andWhere('c.date is null or c.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
             $qb->andWhere('c.date is null or c.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }     
   try {
    $qb->select('count(DISTINCT c.date) as nombrejours');
         return $qb->getQuery()->getSingleScalarResult();  
   } catch (NoResultException $e) {
        return 0;
     }
  } 
}
