<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public   function workedSuperviseur($startDate=null, $endDate=null,$all=false){

        $qb = $this->createQueryBuilder('u')
        ->leftJoin('u.pointVentes','p')
        ->leftJoin('u.ressources','ba')
        ->andWhere('u.type=:type')->setParameter('type','superviseur')
         ->select('u.id')
         ->addSelect('u.username')
         ->addSelect('u.nom')
         ->addSelect('count(p.id) as pdvnumber')
         ->addSelect('count(ba.id) as banumber')
         ->addGroupBy('u.id')
         ->addGroupBy('u.username')
         ->addGroupBy('u.nom');
        return $qb->getQuery()->getArrayResult(); 
  }


}
