parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-54-228-207-163.eu-west-1.compute.amazonaws.com
    database_port: 5432
    database_name: d95fpmthpupd1a
    database_user: sotyhwkzqshjxa
    database_password: 8428943addb3f70dc176553f6d9b6fe2dafaaebf2fced62283fdf2b45e866941
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
