commende_index:
    path:     /commende/list
    defaults: { _controller: "AppBundle:Commende:index"}
    methods:  GET

commende_performances:
    path:     /performances/list
    defaults: { _controller: "AppBundle:Commende:performances"}
    methods:  GET

commende_performances_excel:
    path:     /performances/list/excel
    defaults: { _controller: "AppBundle:Commende:performancesExcel"}
    methods:  GET


commendes_list_insident:
    path:     /{insident}/list/insident
    defaults: { _controller: "AppBundle:Commende:listByInsident" }
    methods:  [GET, POST]

commendes_list:
    path:     /{user}/{pointVente}/{ressource}/list
    defaults: { _controller: "AppBundle:Commende:list", "user":0, "pointVente":0,"ressource":0 }
    methods:  [GET, POST]

commende_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Commende:show" }
    methods:  GET

commende_new:
    path:     /new
    defaults: { _controller: "AppBundle:Commende:new" }
    methods:  [GET, POST]

commendes_news:
    path:     /news
    defaults: { _controller: "AppBundle:Commende:news" }
    methods:  [GET, POST]

commende_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Commende:edit" }
    methods:  [GET, POST]

commende_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Commende:delete" }
    methods:  DELETE
