ressource_index:
    path:     /
    defaults: { _controller: "AppBundle:Ressource:index" }
    methods:  GET

ressource_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Ressource:show" }
    methods:  GET

ressource_new:
    path:     /new
    defaults: { _controller: "AppBundle:Ressource:new" }
    methods:  [GET, POST]

ressource_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Ressource:edit" }
    methods:  [GET, POST]

ressource_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Ressource:delete" }
    methods:  DELETE
